version: 2

models:

    - name: sales
      description: this is sales table.
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: column with the ID for each order.
            tests : 
            - not_null 

          - name: products_id
            description: column with the ID for each product.
            tests:
              - not_null

          - name: qty

          - name: turnover
            description: total turnover from each sale.
            tests:
              - not_null

          - name: purchase_cost
            description: cost of purchasing for the relevant sale.
            tests:
              - not_null

          - name: margin
            description: turnover - purchase cost.